In [28]:
# Instalación 

import sys
# Instala en el MISMO intérprete que usa el kernel
!{sys.executable} -m pip install --upgrade google-cloud-bigquery google-cloud-bigquery-storage pandas-gbq pyarrow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: google-cloud-bigquery in /home/m.lopez/.local/lib/python3.9/site-packages (3.38.0)
Collecting google-cloud-bigquery-storage
  Downloading google_cloud_bigquery_storage-2.33.1-py3-none-any.whl (293 kB)
     |████████████████████████████████| 293 kB 1.4 MB/s
Requirement already satisfied: pandas-gbq in /home/m.lopez/.local/lib/python3.9/site-packages (0.29.2)
Requirement already satisfied: pyarrow in /home/m.lopez/.local/lib/python3.9/site-packages (21.0.0)
Requirement already satisfied: google-api-core[grpc]<3.0.0,>=2.11.1 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-cloud-bigquery) (2.26.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigquery) (2.8.2)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-cloud-bigquery) (2.7.2)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-cloud-bigquery) (2.4.3)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /usr/local/lib/python3.9/site-packages (from google-cloud-bigquery) (2.31.0)
Requirement already satisfied: packaging>=24.2.0 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-cloud-bigquery) (25.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-cloud-bigquery) (2.41.1)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-cloud-bigquery-storage) (1.26.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-cloud-bigquery-storage) (6.32.1)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /home/m.lopez/.local/lib/python3.9/site-packages (from pandas-gbq) (1.4.3)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /home/m.lopez/.local/lib/python3.9/site-packages (from pandas-gbq) (1.2.2)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib64/python3.9/site-packages (from pandas-gbq) (2.1.0)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib64/python3.9/site-packages (from pandas-gbq) (1.25.2)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /home/m.lopez/.local/lib/python3.9/site-packages (from pandas-gbq) (1.9.1)
Requirement already satisfied: setuptools in /usr/lib/python3.9/site-packages (from pandas-gbq) (53.0.0)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.70.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.75.1)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.75.1)
Requirement already satisfied: cachetools<7.0,>=2.0.0 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (6.2.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (4.9.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /home/m.lopez/.local/lib/python3.9/site-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.7.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.9/site-packages (from pandas>=1.1.4->pandas-gbq) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/site-packages (from pandas>=1.1.4->pandas-gbq) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.9/site-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.15.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.0.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib64/python3.9/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2023.5.7)
Requirement already satisfied: typing-extensions~=4.12 in /home/m.lopez/.local/lib/python3.9/site-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (4.15.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /home/m.lopez/.local/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.2.2)
Installing collected packages: google-cloud-bigquery-storage
Successfully installed google-cloud-bigquery-storage-2.33.1

In [32]:
# comprobación de credenciales

import os, google.auth

# Asegúrate de NO forzar una service account:
if os.environ.get("GOOGLE_APPLICATION_CREDENTIALS"):
    print("Quitando GOOGLE_APPLICATION_CREDENTIALS para usar tus credenciales de usuario…")
    os.environ.pop("GOOGLE_APPLICATION_CREDENTIALS", None)

creds, proj = google.auth.default()
print("🔐 Tipo de credenciales:",
      getattr(creds, "service_account_email", "User creds (no service_account_email)"))
print("🧾 ADC project:", proj)

🔐 Tipo de credenciales: User creds (no service_account_email)
🧾 ADC project: None

In [33]:
# Cliente BigQuery + smoke test (SELECT 1)
from google.cloud import bigquery

PROJECT_ID = "mimic-pruebas"  # tu proyecto de cuota
client = bigquery.Client(project=PROJECT_ID)

# Prueba mínima
test_df = client.query("SELECT 1 AS ok", location="US").to_dataframe()
test_df

E0000 00:00:1760591968.527771    8971 alts_credentials.cc:93] ALTS creds ignored. Not running on GCP and untrusted ALTS is not enabled.

   ok
0   1

In [34]:
# primera consulta a MIMIC-IV 
query = """
SELECT COUNT(*) AS pacientes
FROM `physionet-data.mimiciv_3_1_hosp.patients`
"""
df = client.query(query, location="US").to_dataframe()
df

E0000 00:00:1760591974.313600    8971 alts_credentials.cc:93] ALTS creds ignored. Not running on GCP and untrusted ALTS is not enabled.

   pacientes
0     364627

In [1]:
#Si alguna vez ves 403 otra vez

#Revisa que estás autenticada como usuario (celda 2 debe imprimir “User creds…”).

#Desde terminal (no notebook):

#gcloud auth application-default login
#gcloud auth application-default set-quota-project mimic-pruebas